package server

// QWERBandData contains all the band information
var QWERBandData = Band{
	ID:          1,
	Name:        "QWER",
	KoreanName:  "쿼터",
	DebutDate:   "2023-10-18",
	Company:     "Tamago Production",
	Genre:       []string{"K-Pop", "Rock", "Alternative Rock", "Pop Rock"},
	MemberCount: 4,
	Description: "QWER is a South Korean girl band under Tamago Production. They debuted on October 18, 2023, with the mini album 'MANITO'. The band is known for playing their own instruments and having a rock-oriented sound, which is unique in the K-pop industry. Originally created as a virtual project, they transitioned to a real band with actual performances.",
	SocialMedia: map[string]string{
		"youtube":   "https://www.youtube.com/@QWER_official",
		"instagram": "https://www.instagram.com/qwer_official/",
		"twitter":   "https://twitter.com/QWER_official",
		"tiktok":    "https://www.tiktok.com/@qwer_official",
	},
	OfficialSite: "https://qwer-official.com",
	Awards: []Award{
		{Year: 2024, Event: "Asia Artist Awards", Category: "Rookie of the Year – Music", Recipient: "QWER"},
		{Year: 2024, Event: "K-World Dream Awards", Category: "Best Band", Recipient: "QWER"},
		{Year: 2024, Event: "K-World Dream Awards", Category: "Bonsang", Recipient: "QWER"},
		{Year: 2024, Event: "Korea Grand Music Awards", Category: "Best Band", Recipient: "QWER"},
		{Year: 2024, Event: "MAMA Awards", Category: "Best Band Performance", Recipient: "T.B.H"},
		{Year: 2024, Event: "Melon Music Awards", Category: "Hot Trend Award", Recipient: "QWER"},
		{Year: 2025, Event: "Seoul Music Awards", Category: "Main Prize (Bonsang)", Recipient: "QWER"},
	},
	Members: []Member{
		{
			ID:          1,
			Name:        "Hong Jihye",
			StageName:   "Chodan",
			Position:    "Leader, Keyboardist, Vocalist",
			Instrument:  "Keyboard, Piano",
			Birthdate:   "2001-03-15",
			Nationality: "South Korean",
			Height:      "165 cm",
			BloodType:   "A",
			MBTI:        "ENFP",
			Hobbies:     []string{"Composing music", "Playing piano", "Reading"},
			Facts: []string{
				"She is the main composer of the group",
				"Can play multiple instruments including guitar",
				"Studied music composition in college",
				"Known for her bright and energetic personality",
			},
		},
		{
			ID:          2,
			Name:        "Lee Ahhee",
			StageName:   "Magenta",
			Position:    "Lead Guitarist, Sub Vocalist",
			Instrument:  "Electric Guitar, Acoustic Guitar",
			Birthdate:   "2000-08-22",
			Nationality: "South Korean",
			Height:      "162 cm",
			BloodType:   "B",
			MBTI:        "ISTP",
			Hobbies:     []string{"Guitar collecting", "Gaming", "Skateboarding"},
			Facts: []string{
				"Started playing guitar at age 10",
				"Has a collection of over 15 guitars",
				"Known for her cool and mysterious image",
				"Excellent at guitar solos and riffs",
			},
		},
		{
			ID:          3,
			Name:        "Jang Nayoung",
			StageName:   "Hina",
			Position:    "Bassist, Sub Vocalist",
			Instrument:  "Bass Guitar",
			Birthdate:   "2002-12-05",
			Nationality: "Japanese",
			Height:      "160 cm",
			BloodType:   "O",
			MBTI:        "ISFJ",
			Hobbies:     []string{"Cooking", "Photography", "Learning languages"},
			Facts: []string{
				"Fluent in Japanese, Korean, and English",
				"Joined the group as a trainee from Japan",
				"Known for her gentle and caring personality",
				"Often takes care of other members like a mother figure",
			},
		},
		{
			ID:          4,
			Name:        "Lee Si Yeon",
			StageName:   "Siyeon",
			Position:    "Drummer, Main Vocalist",
			Instrument:  "Drums, Percussion",
			Birthdate:   "2003-01-18",
			Nationality: "South Korean",
			Height:      "158 cm",
			BloodType:   "AB",
			MBTI:        "ESFP",
			Hobbies:     []string{"Dancing", "Singing", "Watching movies"},
			Facts: []string{
				"Youngest member of the group",
				"Has the strongest vocal ability in the group",
				"Started as a vocalist but learned drums for the band",
				"Very energetic and playful personality",
			},
		},
	},
	Discography: []Album{
		{
			ID:          1,
			Title:       "MANITO",
			ReleaseDate: "2024-04-01",
			Type:        "Mini Album",
			TrackCount:  7,
			CoverImage:  "/qwer/manito.jpeg",
			Songs: []Song{
				{
					ID:          1,
					Title:       "T.B.H",
					Album:       "MANITO",
					ReleaseDate: "2024-04-01",
					Duration:    "2:55",
					Genre:       "Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/phsDrsw-tzc?si=aqPpB7ICfPa5ZcQt",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/39gaUtq2z4ejJbno7tWHbL?si=2b5332fb3da34a72",
				},
				{
					ID:          2,
					Title:       "SODA",
					Album:       "MANITO",
					ReleaseDate: "2024-04-01",
					Duration:    "2:58",
					Genre:       "Pop Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/SKztjYndS_s?si=bxUR1m9Rd5DGCCQ2",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/0VfOZBCILsIrkJPzw3WdvA?si=040adeb80d654774",
				},
				{
					ID:          3,
					Title:       "Free-Dumb",
					Album:       "MANITO",
					ReleaseDate: "2024-04-01",
					Duration:    "2:38",
					Genre:       "Rock",
					Language:    "Korean",
					YouTubeURL:  "https://www.youtube.com/watch?v=Tor2ElSVEAk",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/5QWkggSHOjxnutRfWyDpSB?si=30a6ddf3d81e4e88",
				},
				{
					ID:          4,
					Title:       "G9JB",
					Album:       "MANITO",
					ReleaseDate: "2024-04-01",
					Duration:    "3:24",
					Genre:       "Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/a0OkChjJWl8?si=OkTKFEsSpNNsiT9Y",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/3wfx8yT3cr1gfD1HZp026n?si=1e236b39033941a5",
				},
				{
					ID:          5,
					Title:       "Ferris Wheel",
					Album:       "MANITO",
					ReleaseDate: "2024-04-01",
					Duration:    "3:40",
					Genre:       "Ballad Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/cmnJZFlKXUU?si=838vvkecnXBldMbC",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/3FoJ70aZmejxNw4rJQSmgo?si=636d94f8024d4b9d",
				},
				{
					ID:          6,
					Title:       "Make Our Highlight",
					Album:       "MANITO",
					ReleaseDate: "2024-04-01",
					Duration:    "3:29",
					Genre:       "Pop Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/HBsU1GpsGKw?si=Gb9quZeKLCpf65VE",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/6K8D5xmpPbk0ql18p9E2GV?si=99f3b2c373734d41",
				},
				{
					ID:          7,
					Title:       "Manito",
					Album:       "MANITO",
					ReleaseDate: "2024-04-01",
					Duration:    "3:15",
					Genre:       "Pop Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/bjq3GHO_Cc0?si=RvEM72SKjFcqwvu6",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/7oubiaqVBOGd91g7Qlx8jv?si=f753447cb7a748ba",
				},
			},
		},
		{
			ID:          2,
			Title:       "Harmony from Discord",
			ReleaseDate: "2023-10-18",
			Type:        "Single Album",
			TrackCount:  4,
			CoverImage:  "/qwer/harmonyfromdiscord.jpeg",
			Songs: []Song{
				{
					ID:          8,
					Title:       "Harmony of Stars",
					Album:       "Harmony from Discord",
					ReleaseDate: "2023-10-18",
					Duration:    "3:29",
					Genre:       "Pop Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/1BTTbopyDWw?si=5vRni-6TLWzCyAFg",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/1b2jcwnf3JwuyWiG3xTPsp?si=119e0ef958d64abc",
				},
				{
					ID:          9,
					Title:       "Discord",
					Album:       "Harmony from Discord",
					ReleaseDate: "2023-10-18",
					Duration:    "2:47",
					Genre:       "Alternative Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/-kcZNuFYnns?si=SYO21RJkY9nS6CYS",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/2kTKlEtnGx5z8oi4O06yqC?si=7fc5a8887f5e4437",
				},
				{
					ID:          10,
					Title:       "Secret Diary",
					Album:       "Harmony from Discord",
					ReleaseDate: "2023-10-18",
					Duration:    "2:41",
					Genre:       "Pop Rock",
					Language:    "Korean",
					YouTubeURL:  "https://www.youtube.com/watch?v=H6alWf2odU8",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/495QLv4XTKlMgcfKXmyuwZ?si=041b8cba9f8c425a",
				},
				{
					ID:          11,
					Title:       "Discord (Inst.)",
					Album:       "Harmony from Discord",
					ReleaseDate: "2023-10-18",
					Duration:    "2:47",
					Genre:       "Alternative Rock",
					Language:    "Instrumental",
					YouTubeURL:  "https://www.youtube.com/watch?v=MWLQruih09w",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/0Tt0kjYSLD1EuQtwyHbZQw?si=8395c7f3950c4cac",
				},
			},
		},
		{
			ID:          3,
			Title:       "Discord (TAK Remix)",
			ReleaseDate: "2023-12-15",
			Type:        "Single",
			TrackCount:  1,
			CoverImage:  "/qwer/discordtakremix.jpeg",
			Songs: []Song{
				{
					ID:          12,
					Title:       "Discord (TAK Remix)",
					Album:       "Discord (TAK Remix)",
					ReleaseDate: "2023-12-15",
					Duration:    "3:12",
					Genre:       "Electronic Rock",
					Language:    "Korean",
					YouTubeURL:  "https://www.youtube.com/watch?v=MZ5lkYhm6xQ",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/0RYILwx3uLBODxIKlT7EUp?si=b5ddeb19aa784740",
				},
			},
		},
		{
			ID:          4,
			Title:       "FAKE IDOL",
			ReleaseDate: "2024-09-02",
			Type:        "Single",
			TrackCount:  1,
			CoverImage:  "/qwer/fake idol.jpeg",
			Songs: []Song{
				{
					ID:          13,
					Title:       "FAKE IDOL",
					Album:       "FAKE IDOL",
					ReleaseDate: "2024-09-02",
					Duration:    "2:39",
					Genre:       "Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/ARORXEnuKgc?si=fztkUsntfEe2q89a",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/4eF3keUr7n9TXSl4NaZQOS?si=05e98ed102fd4a80",
				},
			},
		},
		{
			ID:          5,
			Title:       "Algorithm's Blossom",
			ReleaseDate: "2024-09-23",
			Type:        "Mini Album",
			TrackCount:  8,
			CoverImage:  "/qwer/algorithmblossom.jpeg",
			Songs: []Song{
				{
					ID:          14,
					Title:       "INTRO",
					Album:       "Algorithm's Blossom",
					ReleaseDate: "2024-09-23",
					Duration:    "1:21",
					Genre:       "Intro",
					Language:    "Instrumental",
					YouTubeURL:  "https://youtu.be/Lb3mQdm-UHs?si=42Gb-NKEYzskyu-H",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/1fVhacnwF0vfWinKZ7UvGY?si=e178e460d52f440d",
				},
				{
					ID:          15,
					Title:       "FAKE IDOL",
					Album:       "Algorithm's Blossom",
					ReleaseDate: "2024-09-23",
					Duration:    "2:39",
					Genre:       "Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/ARORXEnuKgc?si=fztkUsntfEe2q89a",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/4CVqLf78QYikxv7CU189fl?si=cde2a18b229549ac",
				},
				{
					ID:          16,
					Title:       "My Name is Malguem",
					Album:       "Algorithm's Blossom",
					ReleaseDate: "2024-09-23",
					Duration:    "3:08",
					Genre:       "Pop Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/AlirzLFEHUI?si=q0SGi2KoNLHQpT1z",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/1lTBkwEm0wim9RsMXqtqWy?si=53c55aad988a4e17",
				},
				{
					ID:          17,
					Title:       "Let's Love",
					Album:       "Algorithm's Blossom",
					ReleaseDate: "2024-09-23",
					Duration:    "2:52",
					Genre:       "Pop Rock",
					Language:    "Korean",
					YouTubeURL:  "https://www.youtube.com/watch?v=TnMOs2eWYIs",
					SpotifyURL:  "https://open.spotify.com/track/letslove",
				},
				{
					ID:          18,
					Title:       "run! run! run!",
					Album:       "Algorithm's Blossom",
					ReleaseDate: "2024-09-23",
					Duration:    "3:09",
					Genre:       "Rock",
					Language:    "Korean",
					YouTubeURL:  "https://www.youtube.com/watch?v=txAakIbx4lA",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/1y8bXrHTm5BqtO2v9eTqXo?si=212a658535c5424c",
				},
				{
					ID:          19,
					Title:       "Goodbye My Sadness",
					Album:       "Algorithm's Blossom",
					ReleaseDate: "2024-09-23",
					Duration:    "4:31",
					Genre:       "Ballad Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/5riuR07c8Dc?si=VGXBzXVc_7dXG2xh",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/7BoC7eEStVxZSBeLtLSoHv?si=d2739cc4524240e2",
				},
				{
					ID:          20,
					Title:       "REBOUND",
					Album:       "Algorithm's Blossom",
					ReleaseDate: "2024-09-23",
					Duration:    "3:32",
					Genre:       "Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/5kf41s91RE8?si=lXLcCpAHqAvQg6_o",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/3loTXGyiVFwxpA40vL8KCj?si=b26673cdb3804f7c",
				},
				{
					ID:          21,
					Title:       "OUTRO",
					Album:       "Algorithm's Blossom",
					ReleaseDate: "2024-09-23",
					Duration:    "1:12",
					Genre:       "Outro",
					Language:    "Instrumental",
					YouTubeURL:  "https://youtu.be/1xEYv_fd-II?si=QVri2B7R_JaOKQ7I",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/7jfgOg18RWa3xk6BLPYYmU?si=90878508110a4a14",
				},
			},
		},
		{
			ID:          6,
			Title:       "In a Million noises, i'll be your harmony",
			ReleaseDate: "2025-06-09",
			Type:        "Mini Album",
			TrackCount:  6,
			CoverImage:  "/qwer/inamillionnoises.jpeg",
			Songs: []Song{
				{
					ID:          22,
					Title:       "Dear",
					Album:       "In a Million noises, i'll be your harmony",
					ReleaseDate: "2025-06-09",
					Duration:    "3:22",
					Genre:       "Pop Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/aeyex4Dg3nE?si=jKKWgifLrHE4ZSfb",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/2ryzy7LSXUDFg5G05znHsL?si=e3583dd1b9e941cf",
				},
				{
					ID:          23,
					Title:       "Be Happy",
					Album:       "In a Million noises, i'll be your harmony",
					ReleaseDate: "2025-06-09",
					Duration:    "2:49",
					Genre:       "Pop Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/PRH8JkIe0Ho?si=ick2Q4t77pV3z4rK",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/2Npv05ajDEnZ1umAlSEE06?si=555f2709842d41b8",
				},
				{
					ID:          24,
					Title:       "#QWER",
					Album:       "In a Million noises, i'll be your harmony",
					ReleaseDate: "2025-06-09",
					Duration:    "2:40",
					Genre:       "Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/8-XjAXrS0bs?si=fELRUYTMyXE9PFiA",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/5uDTOaBVYp18jgdQpHGqbR?si=31977f0686004b21",
				},
				{
					ID:          25,
					Title:       "OVERDRIVE",
					Album:       "In a Million noises, i'll be your harmony",
					ReleaseDate: "2025-06-09",
					Duration:    "2:52",
					Genre:       "Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/kdPfMUAzmSo?si=Fiq0Em4tJVn5-ycb",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/2wVjE1zphtVqitk7LKelKq?si=985159d2195a4b82",
				},
				{
					ID:          26,
					Title:       "D-Day",
					Album:       "In a Million noises, i'll be your harmony",
					ReleaseDate: "2025-06-09",
					Duration:    "2:54",
					Genre:       "Pop Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/YCaTtV9zu6A?si=R3XKP4GsyEXaCJF_",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/4G5iKn17PpZa9O8pcIpGfI?si=ee79c39157fe4878",
				},
				{
					ID:          27,
					Title:       "Yours Sincerely",
					Album:       "In a Million noises, i'll be your harmony",
					ReleaseDate: "2025-06-09",
					Duration:    "3:02",
					Genre:       "Ballad Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/-Fz2vfp4BdY?si=A9bwCzSNC3nSl10W",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/5qwR0wO4SgTyg70ob5Gb3I?si=a2d6a4ca6036457e",
				},
			},
		},
		{
			ID:          7,
			Title:       "Youth Promise (청춘서약)",
			ReleaseDate: "2024-12-09",
			Type:        "Digital Single",
			TrackCount:  1,
			CoverImage:  "/qwer/youthpromise.jpeg",
			Songs: []Song{
				{
					ID:          28,
					Title:       "Youth Promise (청춘서약)",
					Album:       "Youth Promise (청춘서약)",
					ReleaseDate: "2024-12-09",
					Duration:    "3:13",
					Genre:       "Pop Rock",
					Language:    "Korean",
					YouTubeURL:  "https://youtu.be/CGvqj7bzCVY?si=O8GULTttoep5BzKj",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/6S9gXG6Qi9KJkQEdAtcXd6?si=df09b41d644146d0",
				},
			},
		},

		{
			ID:          9,
			Title:       "Discord (Japanese Ver.)",
			ReleaseDate: "2025-05-10",
			Type:        "Digital Single",
			TrackCount:  1,
			CoverImage:  "/qwer/discordjapanesever.jpeg",
			Songs: []Song{
				{
					ID:          30,
					Title:       "Discord (Japanese Ver.)",
					Album:       "Discord (Japanese Ver.)",
					ReleaseDate: "2025-05-10",
					Duration:    "2:47",
					Genre:       "Alternative Rock",
					Language:    "Japanese",
					YouTubeURL:  "https://youtu.be/FOP5Y-OJB1I?si=z7rxizIYq63zE3Df",
					SpotifyURL:  "https://open.spotify.com/intl-id/track/6YQ6VHhyDUXcvNFmCTRrcF?si=d20518ebd1ef4729",
				},
			},
		},
		{
			ID:          10,
			Title:       "PLAY, WE, DEW",
			ReleaseDate: "2025-05-19",
			Type:        "Promotional Single",
			TrackCount:  1,
			Songs: []Song{
				{
					ID:          31,
					Title:       "PLAY, WE, DEW",
					Album:       "PLAY, WE, DEW",
					ReleaseDate: "2025-05-19",
					Duration:    "3:30",
					Genre:       "Pop Rock",
					Language:    "Korean",
					YouTubeURL:  "https://www.youtube.com/watch?v=8IMPpF2tIWI",
					SpotifyURL:  "https://open.spotify.com/track/",
				},
			},
		},
	},
}
